name: Preview cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Surge CLI
        run: npm install -g surge

      - name: Remove Surge deployment
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_NAME=${{ github.event.repository.name }}
          DOMAIN="${REPO_NAME}-pr-${PR_NUMBER}.surge.sh"
          
          echo "Removing deployment: https://${DOMAIN}"
          surge teardown https://${DOMAIN} --token $SURGE_TOKEN || echo "Deployment may have already been removed"

      - name: Comment PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoName = context.payload.repository.name;
            const domain = `${repoName}-pr-${prNumber}.surge.sh`;
            
            const body = [
              '## 🧹 Preview Cleanup',
              '',
              `The preview deployment \`https://${domain}\` has been removed.`,
              '',
              '_Thank you for contributing!_'
            ].join('\n');
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body
            });
